version: '3'

services:
  db:
    image: mariadb:10.8.3
    container_name: "mariadb"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
        - 3306:3306
    volumes:
        - ./.docker/db:/var/lib/mysql
    networks:
        - review-network

  laravel:
    image: alan01777/php8.1-laravel-mariadb:latest
    container_name: laravel
    restart: always
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - review-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./.docker/nginx/conf:/etc/nginx/conf.d
      - ./.docker/nginx/log:/var/log/nginx
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - laravel
    networks:
      - review-network


networks:
  review-network:
    driver: bridge
